swagger: '2.0'
info:
  description: VSBO Service Rest API with Swagger.
  version: '1.0.0'
  title: APITEST For VSBP Service API
  termsOfService: /
  contact:
    name: hujilong WX170734
  license:
    name: APITEST License
schemes:
  - http
host: '10.10.10.10:19315'
basePath: /rest/iothub/services/notification/esimplus/{ASP}
paths:
  '/handleDownloadProgressInfo':
    post:
      tags:
        - handleDownloadProgressInfo
      summary: 'handleDownloadProgressInfo'
      description: 'handleDownloadProgressInfo'
      operationId: handleDownloadProgressInfoPost
      consumes:
        - application/json;charset=utf-8
      produces:
        - application/json;charset=utf-8
      parameters:
        - in: header
          name: country
          type: string
          required: false
          description: 'The ASP notify the receipt url.'
        - in: header
          name: providerId
          type: string
          required: false
          description: 'Basic-Header: Authorization Username="xxx",Password="xxx"'
        - in: header
          name: enterpriseId
          type: string
          required: false
          description: 'Operator identification value that must be configured in PMC.'
        - in: header
          name: AspCallBackUrl
          type: string
          required: false
          description: '"X-Admin-Protocol" header'
        - in: header
          name: X-Admin-Protocol
          type: string
          required: false
          description: '"X-Admin-Protocol" header'
        - in: header
          name: version
          type: string
          required: true
          description: 'Protocol version.
                        Set this parameter to 4.0 in this version.'
        - in: header
          name: traceUniqueID
          type: string
          required: true
          description: 'The coding format of this parameter is AAAAAAAXXXXBBBBBBBBBBBBCCCCDDD, which contains 30 digits in total.
                        AAAAAAA indicates the type of the first component that generates TraceUniqueID. The classification method can be the same as that of module IDs of current products. If the type contains less than 7 digits, pad the type with leading zeros.
                        XXXX distinguishes the nodes of a component deployed on a cluster. The value of XXXX is the sum of the four bytes in an IP address of a node. For example, if the IP address of a node is 192.168.10.2, the value of XXXX is 0372.
                        BBBBBBBBBBBB is dynamically generated by the first component that generates TraceUniqueID. The entry component must ensure that the values of traceUniqueID in different messages are unique. It is recommended that BBBBBBBBBBBB should be generated as YYMMDDHHMMSS. Where, YY indicates the year, such as 09; the first MM indicates the month, such as 08; DD indicates the day, such as 31; HH indicates the hour, such as 13; the second MM indicates the minute, such as 31; SS'
        - in: header
          name: sourceDeviceType
          type: string
          required: true
          description: 'Source device type:
                        18: SAG
                        54: GWS
                        0: IB'
        - in: header
          name: sourceDeviceCode
          type: string
          required: true
          description: 'Source device code, which identifies a device.'
        - in: header
          name: destDeviceType
          type: string
          required: true
          description: 'Destination device type.
                        The values are the same as those of sourceDeviceType.
                        The value of destDeviceType contained in a message sent to the IB is 0.'
        - in: header
          name: destDeviceCode
          type: string
          required: true
          description: 'Destination device code.
                        The destination device code contained in a message sent to the IB is the device code of the IB.'
        - in: header
          name: timestamp
          type: string
          required: true
          description: 'Timestamp.
                        The time must be a UTC time in the format YYYYMMDDHHMMSS.'
        - in: header
          name: authenticatorSource
          type: string
          required: true
          description: 'Authentication code of a source device.
                        It is generated by encrypting, sharedSecret, by the BASE64 algorithm.
                        The default value of sharedSecret is eSIM'

        - in: body
          name: handleDownloadProgressInfoReq
          description: handleDownloadProgressInfo request object
          required: true
          schema:
            $ref: '#/definitions/handleDownloadProgressInfoReq'
      responses:
        '204':
          description: NO-CONTENT


definitions:
  handleDownloadProgressInfoReq:
    type: object
    required:
      - header
    description: 'handleDownloadProgressInfoReq'
    properties:
      header:
        $ref: '#/definitions/headerReqObj'
      eid:
        type: string
        minimum: 1
        maximum: 32
        description: 'Identifies the targeted eUICC. This information SHALL be set if available to the SM-DP+'
      iccid:
        type: string
        minimum: 1
        maximum: 20
        description: 'Identifies the Profile to download and install in the eUICC.'
      profileType:
        type: string
        minimum: 1
        maximum: 128
        description: 'Identifies the Profile Type to download and install in the eUICC.'
      timestamp:
        type: string
        minimum: 0
        maximum: 35
        description: 'Indicates the date/time when the operation has been performed. String format as specified by W3C: YYYY-MMDDThh:mm:ssTZD (E.g. 2001-12-17T09:30:47Z)'
      notificationPointId:
        type: integer
        description: "Indicates the step reached within the Profile Download and Installation procedure.
                      Defined check points are:
                      '1' → Eligibility and retry limit check
                       '2' → Confirmation Code check
                       '3' → BPP download
                       '4' → BPP installation
                       '101' → Profile Enabled
                       '102' → Profile Disabled
                       '103' → Profile Deleted.
                       '10x' notification point are proprietary implementation.
                       The value can be configure for each MNO. Each MNO can be configure to receive these notifications or not (additionaly to configuration to requeste ES9+ corresponding notification in the Profile Meta data). For notificationPoint '1', '2' and '3', the MNO can be configure to receive only failed notifications"
      notificationPointStatus:
        $ref: '#/definitions/FunctionExecutionStatusType'
        description: 'Indicates the status after the execution of the notification point. The ExecutionStatus type is re-used to specify the result of processing of the operation related to the notification point (Executed-Success, Executed-WithWarning, Failed, Expired), and optionally to provide information on any encountered problem (status code, data/object that causes the status code, and message to provide textual and human readable explanation of the status code). NOTE: Executed-WithWarning will not be used in this release.'
      resultData:
        type: string
        minimum: 0
        maximum: 512
        description: 'The finalResult data object as contained in the ProfileInstallationResult, when received from the eUICC'
      operatorId:
        type: string
        minimum: 0
        maximum: 128
        description: 'A proprietary field for ES2+ Client to identify sis-operator and to give a way to manage a request rooting by ES2+ Client. This field will be present if the operatorId was present in the downloadOrder request.'
      tac:
        type: string
        minimum: 0
        maximum: 512
        description: 'Device tac target where a subscription should be downloaded. This information will be there or not depending on platform owner setting'
      imei:
        type: string
        minimum: 0
        maximum: 20
        description: 'Device IMEI target where a subscription should be downloaded. This information will be there or not depending on platform owner setting.'

  headerReqObj:
    type: object
    required:
      - functionCallIdentifier
      - functionRequesterIdentifier
    description: 'Header request type Object.'
    properties:
      functionCallIdentifier:
        type: string
        minimum: 1
        maximum: 100
        description: 'Identification of the function call. '
      functionRequesterIdentifier:
        type: string
        minimum: 1
        maximum: 100
        description: 'Identification of the function requester.'

  FunctionExecutionStatusType:
    type: object
    required:
      - status
    description: 'Wether the function has been processed correctly or not.'
    properties:
      status:
        type: string
        minimum: 1
        maximum: 25
        description: 'Textual and human readable explanation. '
      statusCodeData:
        type: object
        $ref: '#/definitions/StatusCodeDataType'

  StatusCodeDataType:
    type: object
    required:
      - reasonCode
      - subjectCode
    description: 'statusCodeData'
    properties:
      message:
        type: string
        minimum: 0
        maximum: 500
        description: 'Textual and human readable explanation. '
      reasonCode:
        type: string
        minimum: 1
        maximum: 5
        description: 'OID of the reason code'
      subjectCode:
        type: string
        minimum: 1
        maximum: 5
        description: 'OID of the subject code'
      subjectIdentifier:
        type: string
        minimum: 0
        maximum: 100
        description: 'Identifier of the subject'
