openapi: 3.0.0
info:
  version: 0.0.1
  title: One Time Password SMS
servers:
  - url: http://127.0.0.1:3000/one-time-password-sms/v1
paths:
  /send-code:
    post:
      summary: Enviar código OTP
      operationId: sendCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendCodeRequest'
      responses:
        '200':
          description: Código enviado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendCodeResponse'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /validate-code:
    post:
      summary: Validar código OTP
      operationId: validateCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateCodeRequest'
      responses:
        '204':
          description: Código validado exitosamente
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    # Requests
    SendCodeRequest:
      type: object
      required: [phoneNumber, message]
      properties:
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
        message:
          $ref: '#/components/schemas/Message'
    
    ValidateCodeRequest:
      type: object
      required: [authenticationId, code]
      properties:
        authenticationId:
          $ref: '#/components/schemas/AuthenticationId'
        code:
          $ref: '#/components/schemas/Code'
    
    # Responses
    SendCodeResponse:
      type: object
      required: [authenticationId]
      properties:
        authenticationId:
          $ref: '#/components/schemas/AuthenticationId'
    
    Error:
      type: object
      required: [message]
      properties:
        message:
          type: string
          example: "Error description"
    
    # Reusable types
    PhoneNumber:
      type: string
      description: Número en formato E.164 (+346661113334)
      pattern: '^\+[1-9][0-9]{4,14}$'
      example: '+346661113334'
    
    Message:
      type: string
      description: Mensaje SMS con {{code}}
      pattern: .*\{\{code\}\}.*
      maxLength: 160
      example: '{{code}} es tu código'
    
    AuthenticationId:
      type: string
      description: ID único de verificación
      maxLength: 36
      example: 'ea0840f3-3663-4149-bd10-c7c6b8912105'
    
    Code:
      type: string
      description: Código a validar
      maxLength: 10
      example: 'AJY3'
