swagger: "2.0"
info:
  version: "0.0.1"
  title: One Time Password SMS
host: 127.0.0.1:3000
basePath: /one-time-password-sms/v1
schemes:
  - http
consumes:
 - application/json
produces:
  - application/json
paths:
  '/send-code:':
    post:
      description: Returns greetings to the caller
      operationId: hello
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/SendCodeResponse'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  '/validate-code':
    post:
      tags:
        - OTP Management
      summary: Verifies the OTP received as input
      description: |-
        Verifies the code is valid for the received authenticationId
      operationId: validateCode
      parameters:
        - name: x-correlator
          in: header
          description: Correlation id for the different services
          required: false
          type: string
          pattern: ^[a-zA-Z0-9-_:;.\/<>{}]{0,256}$
          example: "b4333c46-49c0-4f62-80d7-f0ef930f1c46"
          schema:
            $ref: '#/definitions/ValidateCodeBody'
      responses:
        '204':
          description: The OTP was successfully validated
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  SendCodeResponse:
    required:
      - message
    properties:
      message:
        type: string
      age:
        type: number
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  SendCodeBody:
    description: Structure to request sending a code to a phone number
    type: object
    properties:
      phoneNumber:
        $ref: '#/definitions/PhoneNumber'
      message:
        $ref: '#/definitions/Message'
    required:
      - message
      - phoneNumber
  SendCodeResponse:
    description: Structure to provide authentication identifier
    type: object
    properties:
      authenticationId:
        $ref: '#/definitions/AuthenticationId'
    required:
      - authenticationId
  ValidateCodeBody:
    description: Strcuture to request code verification
    type: object
    properties:
      authenticationId:
        $ref: '#/definitions/AuthenticationId'
      code:
        $ref: '#/definitions/Code'
    required:
      - authenticationId
      - code
  PhoneNumber:
    description: A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, prefixed with '+'.
    type: string
    pattern: '^\+[1-9][0-9]{4,14}$'
    example: '+346661113334'
  Message:
    type: string
    description: Message template used to compose the content of the SMS sent to the phone number. It must include the following label indicating where to include the short code `{{code}}`
    pattern: .*\{\{code\}\}.*
    maxLength: 160
    example: '{{code}} is your short code to authenticate with Cool App via SMS'
  AuthenticationId:
    type: string
    description: unique id of the verification attempt the code belongs to.
    maxLength: 36
    example: ea0840f3-3663-4149-bd10-c7c6b8912105
  Code:
    type: string
    description: temporal, short code to be validated
    maxLength: 10
    example: AJY3
  ErrorInfo:
    description: Structure to describe error
    type: object
    required:
      - status
      - code
      - message
    properties:
      status:
        type: integer
        description: HTTP response status code
      code:
        type: string
        description: A human-readable code to describe the error
      message:
        type: string
        description: A human-readable description of what the event represents